### ISSUE TITLE
import not working in NextJS app

### ISSUE THREAD

**Issue by davidfant** [great-expectations/jsonforms-antd-renderers#84]
first of all, super happy i found this repo! i was going to implement the basics of this myself, but y'all seem to already have made a great job!

when importing the lib in a NextJS app i get the below error:
```
Error: Cannot find module './renderer-registry-entries'
Require stack:
- /Users/fant/repos/ai/petridish/lab/.next/server/vendor-chunks/@great-expectations.js
- /Users/fant/repos/ai/petridish/lab/.next/server/webpack-runtime.js
- /Users/fant/repos/ai/petridish/lab/.next/server/app/petridish/[petridishId]/v/[versionId]/[view]/page.js
    at __webpack_require__ (/Users/fant/repos/ai/petridish/lab/.next/server/webpack-runtime.js:33:43)
    at eval (./src/components/petridish/trace/TraceList.tsx:24:102)
    at (ssr)/./src/components/petridish/trace/TraceList.tsx (/Users/fant/repos/ai/petridish/lab/.next/server/app/petridish/[petridishId]/v/[versionId]/[view]/page.js:345:1)
    at Object.__webpack_require__ [as require] (/Users/fant/repos/ai/petridish/lab/.next/server/webpack-runtime.js:33:43)
digest: "1312251077"
 GET /petridish/7bf37335-8787-59ca-95a2-061dfafb66ff/v/e9acb592-6b0d-4612-8e15-d25b0c00728f/chat 500 in 6977ms
 ⚠ ./src/components/petridish/trace/TraceList.tsx
Attempted import error: 'rendererRegistryEntries' is not exported from '@great-expectations/jsonforms-antd-renderers' (imported as 'rendererRegistryEntries').

Import trace for requested module:
./src/components/petridish/trace/TraceList.tsx

./src/components/petridish/trace/TraceList.tsx
Attempted import error: 'cellRegistryEntries' is not exported from '@great-expectations/jsonforms-antd-renderers' (imported as 'cellRegistryEntries').

Import trace for requested module:
./src/components/petridish/trace/TraceList.tsx
```

when I require it, it works as expected. `renderer-registry-entries.js` exists in lib/esm, where `index.mjs` imports it, but for some reason it's not working. lmk if i can help debug or provide any other information to track down the issue!

**Comment by DrewHoo** [comment]
@davidfant thanks for filing this--can you create a minimal reproducible example using [codesandbox](https://codesandbox.io/p/sandbox/nextjs-5tlgz?file=%2Findex.js) or something similar? I'd be happy to take a look.

**Comment by davidfant** [comment]
@DrewHoo ofc, here you go:
https://github.com/davidfant/jsonforms-antd-renderers-issue-84-repro

**Comment by DrewHoo** [comment]
Thanks @davidfant -- I was able to reproduce it, and just merged a fix for it (and this ticket closed automatically; feel free to reopen if you still have an issue). Release just went out--can you verify that 1.18.0 fixes your issue?
